    # PrePatching main
    
  - name: Create datewise folder 
    local_action:
      module: file
      path: '{{ datewise }}'
      force: yes
      state: directory
      mode: 0755
    run_once: yes
    register: datewise
    
  - name: Set path variable
    set_fact:
      log_path: '{{ datewise.path }}'
    run_once: yes
     
  - name: Create internal logs folder inside datewise
    local_action:
      module: file
      path: '{{ item }}'
      force: yes
      state: directory
      mode: 0755
    with_items:
      - '{{ log_path }}/reports'
      - '{{ log_path }}/results'
      - '{{ log_path }}/patching_status'
    run_once: yes

  - name: create temp all hosts file in ansible controller
    template:
      src: all_play_hosts.j2
      dest: '{{ log_path }}/patching_status/allhosts_temp.txt'
    delegate_to: localhost
    vars:
      my_variable: '{{ ansible_play_hosts_all }}'
    
  - name: create all hosts file in ansible controller
    shell: cat allhosts_temp.txt | sed "s/\[u'//g; s/', u'/\n/g; s/'\]//g" >> allhosts.txt;
           rm -rf allhosts_temp.txt
    args:
      chdir: "{{ log_path }}/patching_status"
    delegate_to: localhost
    run_once: yes
    
  - name: Clean-up previous log files from windows client
    win_file:
      path: "{{ item }}"
      state: absent
    with_items:
      - '{{ logs_source }}'
      - '{{ hotfix_source }}'
      
  - name: copy template to destination
    template:
      src: patch-report-template.j2
      dest: "{{ logs_source }}"
  
  - name: Configure the windows update and ssh service
    win_service:
      name: "{{ item }}"
      state: started
      start_mode: auto
    with_items:
      - wuauserv
      - ssh-agent
    ignore_errors: yes
    
  - name: PowerShell | Install required module
    win_psmodule: 
      name: PswindowsUpdate
      state: Present
  
  - name: Getting pending reboot status
    win_pending_reboot:
    register: pending_reboot
  
  - name: Print Pending_reboot variable
    debug:
      var: pending_reboot
      
  - name: Print reboot status on host machines
    debug: 
      msg: Initial Reboot is required on the server {{ inventory_hostname }}
    when: pending_reboot.reboot_required == true
  
  - name: Reboot server if required
    win_reboot:
      reboot_timeout: 900
    when: pending_reboot.reboot_required == true