[G1]
test1 ansible_shell_type=cmd ansible_host=10.10.10.10 ansible_user=ansible_admin
[G2] 
test2 ansible_shell_type=cmd ansible_host=20.20.20.20 ansible_user=ansible_admin
[G3]
test3 ansible_shell_type=cmd ansible_host=30.30.30.30 ansible_user=ansible_admin
