# Post Patching main

  - name: Control Node | Update failed servers file
    local_action:
      module: lineinfile
      path: "{{ log_path }}/patching_status/failed.txt"
      insertafter: EOF
      line: "{{ inventory_hostname }}"
      create: yes
    when: update_count is undefined or update_count.found_update_count != update_count.installed_update_count
    ignore_errors: true

  - name: Control Node | Update patched servers file
    local_action:
      module: lineinfile
      path: "{{ log_path }}/patching_status/patched.txt"
      insertafter: EOF
      line: "{{ inventory_hostname }}"
      create: yes
    when: update_count.found_update_count == update_count.installed_update_count
    ignore_errors: true

  - name: Managed Node | Checking last reboot time
    win_shell: Get-CimInstance -ComputerName localhost -Class CIM_OperatingSystem -ErrorAction Stop | Select-Object CSName, LastBootUpTime
    register: lastbootuptime

  - name: Control Node | Printing last boot uptime of managed nodes
    debug:
      var: lastbootuptime.stdout_lines[3]

  - name: Managed Node | Generate hotfix information of last 24 hrs
    win_shell: |
      Get-HotFix | Select-Object Pscomputername,description,hotfixid,installedby,installedon | `
      Where-Object {$_.installedon -gt (get-date).Addhours(-24)} | Export-Csv -NoTypeInformation -Force C:\hotfix.csv

  - name: Managed Node | Collect hotfix information
    fetch:
      src: "{{ hotfix_source }}"
      dest: '{{ log_path }}/reports/{{ inventory_hostname }}_hotfix.csv'
      flat: yes

  - name: Control Node | Generating hotfix final report
    run_once: yes
    delegate_to: localhost
    shell: "cat reports/*_hotfix.csv >> results/final-hotfix.csv"
    args:
      chdir: "{{ log_path }}"

  - name: Control Node | Read final hotfix report's content
    run_once: yes
    delegate_to: localhost
    shell: "cat {{ log_path }}/results/final-hotfix.csv"
    register: finalhotfix

  - name: Control Node | Print final hotfix report's content
    debug:
      var: finalhotfix.stdout_lines
    run_once: yes

  - name: Managed Node | Clean-up previous log files from windows client
    win_file:
      path: "{{ item }}"
      state: absent
    with_items:
      - '{{ logs_source }}'
      - '{{ hotfix_source }}'

  - name: Control Node | Create sorted allhosts and patched files
    shell: sort allhosts.txt > sorted_allhosts.txt;
          sort patched.txt > sorted_allpatched.txt;
    args:
      chdir: "{{ log_path }}/patching_status"
    delegate_to: localhost
    run_once: yes

  - name: Control Node | Create failed-unreachable file
    shell: comm -23 sorted_allhosts.txt sorted_allpatched.txt > failed_unreachable.txt;
          rm -rf sorted_allhosts.txt sorted_allpatched.txt
    args:
      chdir: "{{ log_path }}/patching_status"
    delegate_to: localhost
    run_once: yes

  - name: Control Node | Read allhosts file's content
    shell: cat allhosts.txt
    args:
      chdir: '{{ log_path }}/patching_status'
    delegate_to: localhost
    run_once: yes
    register: allhostsfile

  - name: Control Node | Print allhosts file's content
    debug:
      var: allhostsfile.stdout_lines
    run_once: yes

  - name: Control Node | Read patched file's content
    shell: cat patched.txt
    args:
      chdir: '{{ log_path }}/patching_status'
    delegate_to: localhost
    run_once: yes
    register: patchedfile

  - name: Control Node | Print patched file's content
    debug:
      var: patchedfile.stdout_lines
    run_once: yes

  - name: Control Node | Read failed_unreachable file's content
    shell: cat failed_unreachable.txt
    args:
      chdir: '{{ log_path }}/patching_status'
    delegate_to: localhost
    run_once: yes
    register: failed_unreachablefile

  - name: Control Node | Print failed_unreachable file's content
    debug:
      var: failed_unreachablefile.stdout_lines
    run_once: yes
